package Vista;
//Segunda interfaz del proyecto
// Autor: Alexis
import Modelo.Autores;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class GestionAutores extends javax.swing.JInternalFrame {
    
 ArrayList<Autores> listaautores= new ArrayList<>();
 int indice=-1;

    public GestionAutores() {
        initComponents();
    }
    private void limpiarCampos(){
        this.jtextfieldnombre.setText("");
        this.jtextfieldid.setText("");
        this.jtextfieldfecha.setText("");
        this.jtextfieldemail.setText("");
        this.jtextfieldapellidos.setText("");
        this.jtextfieldcedula.setText("");
    }
     private void llenarTabla(){
    DefaultTableModel modelo= new DefaultTableModel();
     String [] columnas = {"id", "Nombre", "Apellidos", "Cedula", "FechaNac", "Email"};
             modelo.setColumnIdentifiers(columnas);
             for(Autores pro:listaautores){
                String [] renglon = {
                    pro.getId(),
                    pro.getNombres(),
                    pro.getApellidos(),
                    pro.getCedula(),
                    pro.getFechaNac(),
                    pro.getEmail()
                                     };
                    
                    modelo.addRow(renglon);
                 }
             jtableautores.setModel(modelo);
             }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtableautores = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jtextfieldid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtextfieldnombre = new javax.swing.JTextField();
        jtextfieldapellidos = new javax.swing.JTextField();
        jtextfieldcedula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jbuttonactualizar = new javax.swing.JButton();
        jbuttonborrar1 = new javax.swing.JButton();
        jbuttonagregar = new javax.swing.JButton();
        jbuttonlimpiar = new javax.swing.JButton();
        jbuttoneditar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtextfieldfecha = new javax.swing.JTextField();
        jtextfieldemail = new javax.swing.JTextField();

        setBackground(new java.awt.Color(81, 81, 80));
        setBorder(null);
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtableautores.setBackground(new java.awt.Color(146, 114, 114));
        jtableautores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(jtableautores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 680, 200));

        jPanel3.setBackground(new java.awt.Color(39, 39, 39));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rivas\\OneDrive\\Pictures\\Screenshots\\Captura de pantalla 2025-11-08 121329.png")); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 90, 70));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Solicitar entrada de los clientes");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 290, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 50));

        jPanel4.setBackground(new java.awt.Color(146, 114, 114));
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 680, 50));

        jtextfieldid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfieldidActionPerformed(evt);
            }
        });
        getContentPane().add(jtextfieldid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 170, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("ID DEL CLIENTE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Nombres");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));
        getContentPane().add(jtextfieldnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 170, -1));
        getContentPane().add(jtextfieldapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 170, -1));
        getContentPane().add(jtextfieldcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 170, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Tipo pago");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("Fecha nac");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jPanel5.setBackground(new java.awt.Color(39, 39, 39));
        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 670, 70));

        jPanel1.setBackground(new java.awt.Color(81, 81, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbuttonactualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbuttonactualizar.setForeground(new java.awt.Color(255, 51, 51));
        jbuttonactualizar.setText("Actualizar");
        jbuttonactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonactualizarActionPerformed(evt);
            }
        });
        jPanel1.add(jbuttonactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 100, -1));

        jbuttonborrar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbuttonborrar1.setForeground(new java.awt.Color(255, 51, 51));
        jbuttonborrar1.setText("Borrar");
        jbuttonborrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonborrar1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbuttonborrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, -1));

        jbuttonagregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbuttonagregar.setForeground(new java.awt.Color(255, 51, 51));
        jbuttonagregar.setText("Agregar");
        jbuttonagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonagregarActionPerformed(evt);
            }
        });
        jPanel1.add(jbuttonagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jbuttonlimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbuttonlimpiar.setForeground(new java.awt.Color(255, 51, 51));
        jbuttonlimpiar.setText("Limpiar");
        jbuttonlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonlimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(jbuttonlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        jbuttoneditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbuttoneditar.setForeground(new java.awt.Color(255, 51, 51));
        jbuttoneditar.setText("Editar");
        jbuttoneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttoneditarActionPerformed(evt);
            }
        });
        jPanel1.add(jbuttoneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Genero");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));
        jPanel1.add(jtextfieldfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 170, -1));

        jtextfieldemail.setText("jTextField1");
        jPanel1.add(jtextfieldemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 190, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 680, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuttonlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonlimpiarActionPerformed
    limpiarCampos();
    }//GEN-LAST:event_jbuttonlimpiarActionPerformed

    private void jbuttonagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonagregarActionPerformed
         if((jtextfieldnombre.getText().contentEquals(""))||
             (jtextfieldapellidos.getText().contentEquals("")||
             (jtextfieldcedula.getText().contentEquals(""))||
             (jtextfieldid.getText().contentEquals(""))||
             (jtextfieldfecha.getText().contentEquals(""))||
             (jtextfieldemail.getText().contentEquals("")))){
         JOptionPane.showMessageDialog(null, "algunos campos estan vacios", "Revise todos los campos!",JOptionPane.WARNING_MESSAGE);
         
         }else{
                 String nombre =this.jtextfieldnombre.getText();
                 String apellido = this.jtextfieldapellidos.getText();
                 String cedula = this.jtextfieldcedula.getText();
                 String id = this.jtextfieldid.getText();
                 String fecha = this.jtextfieldfecha.getText();
                 String email = this.jtextfieldemail.getText();
                 
         try{
             Autores autor =new Autores (id , nombre , apellido , cedula, fecha , email);
             this.limpiarCampos();
             this.listaautores.add(autor);
             JOptionPane.showMessageDialog(null, "Datos agregados correctamente");
             
              }catch(Exception e){
                  JOptionPane.showMessageDialog(null,"Datos no agregados","Error", JOptionPane.WARNING_MESSAGE);
              }
         llenarTabla(); 
      JOptionPane.showMessageDialog(null, "Datos agregados correctamente"); 
       }     
    }//GEN-LAST:event_jbuttonagregarActionPerformed

    private void jbuttonborrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonborrar1ActionPerformed
        int fila = this.jtableautores.getSelectedRow();
        if (fila == -1){
         JOptionPane.showMessageDialog(rootPane, "Seleccione un registro de la tabla");
    
         }else{
          JDialog.setDefaultLookAndFeelDecorated(true);
          int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar?" , "Eliminando..." , JOptionPane.YES_NO_OPTION , JOptionPane.QUESTION_MESSAGE);
          
          if (resp == JOptionPane.YES_OPTION){
              listaautores.remove(fila);
              llenarTabla();
          }
        }      
    }//GEN-LAST:event_jbuttonborrar1ActionPerformed

    private void jbuttoneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttoneditarActionPerformed
     int fila = this.jtableautores.getSelectedRow();
      if (fila == -1) {
          JOptionPane.showMessageDialog(rootPane,"Seleccione un registro de la tabla");
          
     }else{
          String id = (String) this.jtableautores.getValueAt(fila, 0);
          String nom = (String) this.jtableautores.getValueAt(fila, 1);
          String ape = (String) this.jtableautores.getValueAt(fila, 2);
          String ced = (String) this.jtableautores.getValueAt(fila, 3);
          String fechaNac = (String) this.jtableautores.getValueAt(fila, 4);
          String email= (String) this.jtableautores.getValueAt(fila, 5);
          
             jtextfieldnombre.setText(nom);
             jtextfieldid.setText(id);
             jtextfieldapellidos.setText(ape);
             jtextfieldcedula.setText(ced);
             jtextfieldfecha.setText(fechaNac);
             jtextfieldemail.setText(email);
             indice =fila;
             }
    }//GEN-LAST:event_jbuttoneditarActionPerformed

    private void jbuttonactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonactualizarActionPerformed
     if((jtextfieldnombre.getText().isEmpty())||
             (jtextfieldapellidos.getText().isEmpty())||
             (jtextfieldid.getText().isEmpty())||
             (jtextfieldemail.getText().isEmpty())||
             (jtextfieldcedula.getText().isEmpty())||
             (jtextfieldfecha.getText().isEmpty())|| indice==-1){     
                JOptionPane.showMessageDialog(null, "Algunos campos estan vacios", "Actualizar...", JOptionPane.WARNING_MESSAGE);
                limpiarCampos();
            }else{
                listaautores.get(indice).setNombres(jtextfieldnombre.getText());
                listaautores.get(indice).setId(jtextfieldid.getText());
                listaautores.get(indice).setApellidos(jtextfieldapellidos.getText());
                listaautores.get(indice).setEmail(jtextfieldemail.getText());
                listaautores.get(indice).setFechaNac(jtextfieldfecha.getText());
                listaautores.get(indice).setCedula(jtextfieldcedula.getText());
                
                llenarTabla();
                limpiarCampos();
                
            }  
    }//GEN-LAST:event_jbuttonactualizarActionPerformed

    private void jtextfieldidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfieldidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfieldidActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbuttonactualizar;
    private javax.swing.JButton jbuttonagregar;
    private javax.swing.JButton jbuttonborrar1;
    private javax.swing.JButton jbuttoneditar;
    private javax.swing.JButton jbuttonlimpiar;
    private javax.swing.JTable jtableautores;
    private javax.swing.JTextField jtextfieldapellidos;
    private javax.swing.JTextField jtextfieldcedula;
    private javax.swing.JTextField jtextfieldemail;
    private javax.swing.JTextField jtextfieldfecha;
    private javax.swing.JTextField jtextfieldid;
    private javax.swing.JTextField jtextfieldnombre;
    // End of variables declaration//GEN-END:variables
}
