package Vista;
//Vista principal del proyecto
//
//autor: Alexis
import Modelo.CLIENTE;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

public class NewJInternalFrame extends javax.swing.JInternalFrame {
     ArrayList<CLIENTE> listacliente= new ArrayList<>();
     int indice= -1;
     boolean modoEdicion = false;
    public NewJInternalFrame() {
        initComponents();
    }
    private void limpiarCampos(){
        this.jtextfieldnombre.setText("");
        this.jtextfieldid.setText("");
        this.jtextfieldgenero.setText("");
        this.jtextfieldpago.setText("");
        this.jtextfieldinicio.setText("");
    }
    private void llenarTabla(){
    DefaultTableModel modelo= new DefaultTableModel();
     String [] columnas = {"id", "Nombre", "Genero", "Tipo de pago", "Fecha de inicio"};
             modelo.setColumnIdentifiers(columnas);
             for(CLIENTE pro:listacliente){
                String [] renglon = {
                    pro.getId(),
                    pro.getNombre(),
                    pro.getGenero(),
                    pro.getTipopago(),
                    pro.getFechainicio(), };
                    
                    modelo.addRow(renglon);
                 }
             jTableClientes.setModel(modelo);
             }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtextfieldid = new javax.swing.JTextField();
        jtextfieldnombre = new javax.swing.JTextField();
        jtextfieldgenero = new javax.swing.JTextField();
        jtextfieldpago = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtextfieldinicio = new javax.swing.JTextField();
        botonguardar = new javax.swing.JButton();
        JButtonLimpiar = new javax.swing.JButton();
        JButtonEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jButtonEditar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(81, 81, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID del cliente:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Generó:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 60, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo de pago:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 110, 110, -1));

        jtextfieldid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfieldidActionPerformed(evt);
            }
        });
        jPanel2.add(jtextfieldid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 100, -1));
        jPanel2.add(jtextfieldnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 100, -1));
        jPanel2.add(jtextfieldgenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 100, -1));

        jtextfieldpago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfieldpagoActionPerformed(evt);
            }
        });
        jPanel2.add(jtextfieldpago, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 110, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha de inicio:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));
        jPanel2.add(jtextfieldinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 110, -1));

        botonguardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonguardar.setText("Guardar");
        botonguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonguardarActionPerformed(evt);
            }
        });
        jPanel2.add(botonguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        JButtonLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JButtonLimpiar.setText("Limpiar");
        JButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(JButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        JButtonEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JButtonEliminar.setText("Eliminar");
        JButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(JButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        jTableClientes.setBackground(new java.awt.Color(146, 114, 114));
        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(jTableClientes);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 610, 270));

        jButtonEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        jButtonActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\rivas\\OneDrive\\Pictures\\Screenshots\\Captura de pantalla 2025-11-06 141629.png")); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jPanel3.setBackground(new java.awt.Color(146, 114, 114));
        jPanel3.setForeground(new java.awt.Color(146, 114, 114));
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 610, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gestión de clientes/ tipo de membresía");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 340, 30));

        jPanel4.setBackground(new java.awt.Color(39, 39, 39));
        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 590, 60));

        jPanel5.setBackground(new java.awt.Color(39, 39, 39));
        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 610, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 610, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtextfieldidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfieldidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfieldidActionPerformed

    private void jtextfieldpagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfieldpagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfieldpagoActionPerformed

    private void JButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonLimpiarActionPerformed
    limpiarCampos();
       botonguardar.setEnabled(true);
       botonguardar.setBackground(UIManager.getColor("Button.background"));
    }//GEN-LAST:event_JButtonLimpiarActionPerformed

    private void botonguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonguardarActionPerformed
      if((jtextfieldnombre.getText().contentEquals(""))||
             (jtextfieldgenero.getText().contentEquals("")||
             (jtextfieldid.getText().contentEquals(""))||
             (jtextfieldpago.getText().contentEquals(""))||
             (jtextfieldinicio.getText().contentEquals("")))){
         JOptionPane.showMessageDialog(null, "algunos campos estan vacios", "Revise todos los campos!",JOptionPane.WARNING_MESSAGE);
         
         }else{
                 String nombre =this.jtextfieldnombre.getText();
                 String genero = this.jtextfieldgenero.getText();
                 String IdCliente = this.jtextfieldid.getText();
                 String tipoPago = this.jtextfieldpago.getText();
                 String fechaInicio = this.jtextfieldinicio.getText();
                 
         try{
             CLIENTE cliente =new CLIENTE(IdCliente,nombre , genero , tipoPago , fechaInicio);
             this.limpiarCampos();
             this.listacliente.add(cliente);
             JOptionPane.showMessageDialog(null, "Datos agregados correctamente");
             
              }catch(Exception e){
                  JOptionPane.showMessageDialog(null,"Datos no agregados","Error", JOptionPane.WARNING_MESSAGE);
           }
         llenarTabla(); 
      JOptionPane.showMessageDialog(null, "Datos agregados correctamente");
      }
      
             

    }//GEN-LAST:event_botonguardarActionPerformed

    private void JButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonEliminarActionPerformed
   int fila = this.jTableClientes.getSelectedRow();
      if (fila == -1){
     JOptionPane.showMessageDialog(rootPane, "Seleccione un registro de la tabla");
    
     }else{
          JDialog.setDefaultLookAndFeelDecorated(true);
          int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar?" , "Eliminando..." , JOptionPane.YES_NO_OPTION , JOptionPane.QUESTION_MESSAGE);
          
          if (resp == JOptionPane.YES_OPTION){
              listacliente.remove(fila);
              llenarTabla();
          }
                   }
    }//GEN-LAST:event_JButtonEliminarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
     int fila = this.jTableClientes.getSelectedRow();
      if (fila == -1) {
          JOptionPane.showMessageDialog(rootPane,"Seleccione un registro de la tabla");
          
     }else{
          String id = (String) this.jTableClientes.getValueAt(fila, 0);
          String nom = (String) this.jTableClientes.getValueAt(fila, 1);
          String gen = (String) this.jTableClientes.getValueAt(fila, 2);
          String pago = (String) this.jTableClientes.getValueAt(fila, 3);
          String fecha = (String) this.jTableClientes.getValueAt(fila, 4);
          
             jtextfieldnombre.setText(nom);
             jtextfieldgenero.setText(gen);
             jtextfieldid.setText(id);
             jtextfieldpago.setText(pago);
             jtextfieldinicio.setText(fecha);
             indice =fila;
             modoEdicion = true;
                botonguardar.setEnabled(false);
                botonguardar.setBackground(new Color(240, 240, 240));
                botonguardar.setForeground(new Color(150, 150, 150)); 
                botonguardar.setBorder((BorderFactory.createLineBorder(new Color(200, 200, 200))));
                
                
             
             }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
            if((jtextfieldnombre.getText().contentEquals(""))||
             (jtextfieldgenero.getText().contentEquals(""))||
             (jtextfieldid.getText().contentEquals(""))||
             (jtextfieldpago.getText().contentEquals(""))||
             (jtextfieldinicio.getText().contentEquals(""))|| indice==-1){     
                JOptionPane.showMessageDialog(null, "Algunos campos estan vacios", "Actualizar...", JOptionPane.WARNING_MESSAGE);
                limpiarCampos();
            }else{
                listacliente.get(indice).setNombre(jtextfieldnombre.getText());
                listacliente.get(indice).setId(jtextfieldid.getText());
                listacliente.get(indice).setGenero(jtextfieldgenero.getText());
                listacliente.get(indice).setTipopago(jtextfieldpago.getText());
                listacliente.get(indice).setFechainicio(jtextfieldinicio.getText());
                
                llenarTabla();
                limpiarCampos();
                
            }  
    }//GEN-LAST:event_jButtonActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonEliminar;
    private javax.swing.JButton JButtonLimpiar;
    private javax.swing.JButton botonguardar;
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTextField jtextfieldgenero;
    private javax.swing.JTextField jtextfieldid;
    private javax.swing.JTextField jtextfieldinicio;
    private javax.swing.JTextField jtextfieldnombre;
    private javax.swing.JTextField jtextfieldpago;
    // End of variables declaration//GEN-END:variables
}
